[project]
name = "note-taker-mcp"
version = "0.1.0"
dependencies = [
  "mcp[cli]>=1.25.0",
  "smithery>=0.3.1",
  "uvicorn>=0.30.0",
  "sse-starlette>=2.0.0"
]

[project.scripts]
note-taker-mcp = "note_taker_mcp_server:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
